# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright 2024 Beijing ESWIN Computing Technology Co., Ltd.

obj-$(CONFIG_CMD_ESWUPDATE) += eswupdate/
obj-$(CONFIG_CMD_ESWOTP) += eswotp/
obj-$(CONFIG_CMD_ESWUPDATE) += dosfstools/
obj-$(CONFIG_CMD_ESWUPDATE) += lib/
