# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright 2024 Beijing ESWIN Computing Technology Co., Ltd.

obj-$(CONFIG_DRM_ESWIN) += mglib_demo.o mglib_api.o mglib_driver.o
obj-$(CONFIG_DRM_ESWIN) += test/

