# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright 2024 Beijing ESWIN Computing Technology Co., Ltd.

obj-$(CONFIG_CMD_ESWOTP) += es_otp.o
obj-$(CONFIG_CMD_ESWUPDATE) += bootesw.o
obj-$(CONFIG_CMD_ESWUPDATE) += eswupdate.o
obj-$(CONFIG_CMD_ESWUPDATE) += mkfs.fat.o
obj-$(CONFIG_CMD_ESWUPDATE) += es_bootloader.o
